src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    private ?string $confirm = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_convive = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $allergie = null;

    public function __construct(UserPasswordHasherInterface $passwordHasher) {
        $this->passwordHasher = $passwordHasher;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $this->passwordHasher->hashPassword($this,$password);
        return $this;
    }

    /**
     * Get the value of confirm
     */
	public function getConfirm()
	{
	    return $this->confirm;
	}
	
	/**
	 * Set the value of confirm
	 *
	 * @return  self
	 */
	public function setConfirm($confirm)
	{
	    $this->confirm = $confirm;
	
	    return $this;
	}

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNbConvive(): ?int
    {
        return $this->nb_convive;
    }

    public function setNbConvive(?int $nb_convive): self
    {
        $this->nb_convive = $nb_convive;

        return $this;
    }

    public function getAllergie(): ?string
    {
        return $this->allergie;
    }

    public function setAllergie(?string $allergie): self
    {
        $this->allergie = $allergie;

        return $this;
    }

    public function __toString(){
        return $this->email; // Remplacer champ par une propriété "string" de l'entité
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\EqualTo;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Context\ExecutionContext;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("email", TextType::class, [
                "label" => "Adresse email",
                "required" => true,
                "constraints" => [
                    new Length(["min" => 2, "max" => 180, "minMessage" => "L'adresse email ne doit pas faire moins de 2 caractères", "maxMessage" => "L'adresse email' ne doit pas faire plus de 180 caractères"]),
                    new NotBlank(["message" => "L'adresse email ne doit pas être vide !"])
                ]
            ])
            ->add("password", PasswordType::class, [
                "label" => "Mot de passe",
                "required" => true,
                "constraints" => [
                    new NotBlank(["message" => "Le mot de passe ne peut pas être vide !"])
                ]
            ])
            ->add("confirm", PasswordType::class, [
                "label" => "Confirmer le mot de passe",
                "required" => true,
                "constraints" => [
                    new NotBlank(["message" => "Le mot de passe ne peut pas être vide !"]),
                    // new EqualTo(["propertyPath" => "password", "message" => "Les mots de passe doivent être identique !"])
                    new Callback(['callback' => function ($value, ExecutionContext $ec) {
                        if ($ec->getRoot()['password']->getViewData() !== $value) {
                            $ec->addViolation("Les mots de passe doivent être identique !");
                        }
                    }])
                ]
                ])
            ->add('nom')
            //->add('nb_convive')
            ->add("nb_convive", NumberType::class, [
                "label" => "Nombre de convives",
                "required" => true,
                "constraints" => [
                    new NotBlank(["message" => "Le nombre de convives ne peut pas être vide !"])
                ]
            ])
            ->add('allergie');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "data_class" => User::class,
            'csrf_protection' => false,
            'csrf_field_name' => '_token',
            'csrf_token_id'   => 'post_item',
        ]);
    }
}



            
            

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\HoraireRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    // QA-60: seule la page d'inscription doit être disponible à tout le monde
    #[IsGranted('ROLE_ADMIN', message: 'Page réservée à l\'administrateur')]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new')]
    public function new(Request $request, UserPasswordHasherInterface $userPasswordHasher, ManagerRegistry $doctrine): Response
    {
        $user = new User($userPasswordHasher);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager();
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute("app_user_index");
        }
        return $this->render('user/new.html.twig', [
            "form" => $form->createView(),
        ]);
    }


    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    // QA-60: seule la page d'inscription doit être disponible à tout le monde
    #[IsGranted('ROLE_ADMIN', message: 'Page réservée à l\'administrateur')]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    // QA-60: seule la page d'inscription doit être disponible à tout le monde
    #[IsGranted('ROLE_ADMIN', message: 'Page réservée à l\'administrateur')]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    // QA-60: seule la page d'inscription doit être disponible à tout le monde
    #[IsGranted('ROLE_ADMIN', message: 'Page réservée à l\'administrateur')]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btnPrincipal btn">Supprimer</button>
</form>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block body %}
    <h2>Liste des utilisateurs</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Nom</th>
                <th>Nombre de convives</th>
                <th>Allergie</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.nbConvive }}</td>
                <td>{{ user.allergie }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">Afficher</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucune entrée trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    {% block header %} {% endblock %}
    <section class="login_section h-100">
        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
            <div class="card rounded-3 text-black">
                <div class="row g-0">
                    <div class="card-body p-md-5 mx-md-4">
                        <div class="text-center">
                            <img src="{{ asset('img/logo_quai_antique.svg') }}" alt="" width="250" height="75">
                            <h4 class="mt-1 mb-5 pb-1">Créer un espace client</h4>
                        </div>
        
                        <form method="post">
                            {{ form_start(form) }}
                                <div class="my-custom-class-for-errors">
                                    {{ form_errors(form) }}
                                </div>

                                <div class="row">
                                    <div class="col-12">
                                        {{ form_label(form.email) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.email) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.password) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.password) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.confirm) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.confirm) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.nom) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.nom) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.nb_convive) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.nb_convive) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_label(form.allergie) }}
                                    </div>
                                    <div class="col-12">
                                        {{ form_widget(form.allergie) }}
                                    </div>
                                </div>
                            
                            <div class="text-center pt-1 mb-5 pb-1">
                                <a href="/" class="btnPrincipal btn mt-3 mb-3 me-3" type="button">Retour</a>
                                <button class="btnPrincipal btn mt-3 mb-3">{{ button_label|default('Enregistrer') }}</button>
                            </div>
                            {{ form_end(form, {render_rest: false}) }}
                            
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                        {# QA-67: Dans la page inscription, supprimer la dernière partie "Je n'ai pas d'espace client ?"  #}
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <h2>Utilisateur</h2>

    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Nombre de convives</th>
                <td>{{ user.nbConvive }}</td>
            </tr>
            <tr>
                <th>Allergie</th>
                <td>{{ user.allergie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">Retour à la liste</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}